project/Controllers/LogadoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Proj_Interdisciplinar.DAO;
using Proj_Interdisciplinar.Models;
using System;

namespace Proj_Interdisciplinar.Controllers
{
    public class LogadoController : Controller
    {
        protected bool ExigeAutenticacao { get; set; } = true;
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (ExigeAutenticacao && !HelperControllers.VerificaUserLogado(HttpContext.Session))
                context.Result = RedirectToAction("Login", "Login");
            else
            {
                ViewBag.Logado = true;
                base.OnActionExecuting(context);
            }
        }

        public IActionResult InicialLogado(UserViewModel model)
        {
            return View("InicialLogado", model);
        }

        public IActionResult InicialLogadoClient(UserViewModel model)
        {
            return View("InicialLogadoClient", model);
        }

        public IActionResult LogOff()
        {
            try
            {
                HttpContext.Session.Clear();
                return RedirectToAction("Login", "Login");
            }
            catch (Exception erro)
            {
                return View("Error", new ErrorViewModel(erro.Message));
            }
        }
    }
}

project/Views/Logado/InicialLogado.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@section Styles{
    <link rel="stylesheet" type="text/css" href="~/css/InicialLogado.css" />
    <link href="~/css/site.css" rel="stylesheet" />
}
<main>

    <div class="welcome">

        <h1>Bem vindo Administrador(a)</h1>

    </div>



    <article class="content-adm">



        <h1>Operações Gerenciáveis</h1>

        <div class="acoes">

            <a href="/CadastroUsuarios/UsuariosCadastrados?tipo=0" class="addUser"></a>
            <a href="/CadastroUsuarios/UsuariosCadastrados?tipo=1" class="addAdm"></a>

        </div>

        <div class="acoes">

            <a href="/Produto/ProdutosCadastrados" class="addProduct"></a>
            <a href="/Categoria/CategoriasCadastradas" class="addCategory"></a>

        </div>

        <div class="acoes">
            <a href="@Url.Action("LogOff","Logado")" class="logout"></a>
        </div>

    </article>

</main>

project/Views/Logado/InicialLogadoClient.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@section Styles{
    <link rel="stylesheet" type="text/css" href="~/css/InicialLogado.css" />
    <link href="~/css/site.css" rel="stylesheet" />
}

<main>

    <div class="welcome">

        <h1>Bem vindo Cliente</h1>

    </div>



    <article class="content-adm">



        <h1>Operações</h1>

        <div class="acoes">

            <a href="/Compras/Compras" class="compra"></a>
            <a href="/Produto/Produtos" class="search"></a>

        </div>

        <div class="acoes">
            <a href="@Url.Action("LogOff","Logado")" class="logout"></a>
        </div>

    </article>

</main>